local strategies = {
    "1.Ch'ien/ The Creative: As heaven moves with increasing power so the wise becomes strong, untiring",
    "2.K'un/ The Receptive: As it the earth's condition: strong and devoted Thus does the wise carry the outer world",
    "3.Chun/ Reszolving Chaos: By movementin the midst of danger the wise brings order out of confusion ",
    "4.Mêng/ Immaturity: As a clear mountain spring flowing onward, So is the wise: thorough clear and calm",
    "5.Hsü/ Waiting: When clouds rise up to heaven, the wise eats and drinks, he is joyous and of good cheer",
    "6.Sung/ Conflict: Haven and water go their opposite ways. The wise consider their plans' beginings",
    "7.Shih/ The Army: As the earth shelters within it, so does the wise increase their wealth: By generocity towards to their people",
    "8.Pi/ Holding Together: As waters over the earth flow together, so the wise cultivates relationships",
    "9.Hsiao Ch'u/ The Taming Power of the Small: As the gentle wind shapes the clouds, so the wise refones their bearing",
    "10.Lü/ Treading [conduct]: Heaven above lake below: discrimination, thus the wise reassures their people",
    "11.T'ai/ Peace: As heaven and earth unite in due season, so the wise divides and completes. They further and regulate the gifts of heaven and earth",
    "12.P'i/ Standstill [Stagnation]: When heaven and earth do not unite, the wise turn to their inner worth. They dont permit themselves to be honoured",
    "13.T'ung Jên /Fellowship: Heaven with fire: strength with clarity, as the lights in heaven arrange time, so the wise organise society",
    "14.Ta Yu/ Possession in Great Measure: As the sun sheds light on good and evil, so the wise curbs evil and furthers good",
    "15.Ch'ien/ Modesty: Sithin the earth, a mountain. Inner wealth. Thus the wise reduces fullness and augments that which is too little",
    "16.Yü/ Enthusiasm: As thunder resounds out of the earth, so kings of old made music in the temple. To honor merit, a time for awe",
    "Children's voices -speaking -singing",
    "Cluster analysis",
    "Consider different fading systems",
    "Consult other sources -promising -unpromising",
    "Convert a melodic element into a rhythmic element",
    "Courage!",
    "Cut a vital connection",
    "Decorate, decorate",
    "Define an area as `safe' and use it as an anchor",
    "Destroy -nothing -the most important thing",
    "Discard an axiom",
    "Disconnect from desire",
    "Discover the recipes you are using and abandon them",
    "Distorting time",
    "Do nothing for as long as possible",
    "Don't be afraid of things because they're easy to do",
    "Don't be frightened of cliches",
    "Don't be frightened to display your talents",
    "Don't break the silence",
    "Don't stress one thing more than another",
    "Do something boring",
    "Do the washing up",
    "Do the words need changing?",
    "Do we need holes?",
    "Emphasize differences",
    "Emphasize repetitions",
    "Emphasize the flaws",
    "Faced with a choice, do both (given by Dieter Rot)",
    "Feedback recordings into an acoustic situation",
    "Fill every beat with something",
    "Get your neck massaged",
    "Ghost echoes",
    "Give the game away",
    "Give way to your worst impulse",
    "Go slowly all the way round the outside",
    "Honor thy error as a hidden intention",
    "How would you have done it?",
    "Humanize something free of error",
    "Imagine the music as a moving chain or caterpillar",
    "Imagine the music as a set of disconnected events",
    "Infinitesimal gradations",
    "Intentions -credibility of -nobility of -humility of",
    "Into the impossible",
    "Is it finished?",
    "Is there something missing?",
    "Is the tuning appropriate?",
    "Just carry on",
}

return strategies
